#!/usr/bin/env ruby
# frozen_string_literal: true

git_path = File.expand_path('../../.git', __FILE__)

$LOAD_PATH.unshift(File.expand_path('../../lib', __FILE__)) if File.exist?(git_path)

require 'swagger2hyperschema/cli'

Swagger2hyperschema::CLI.new(ARGV).call
